- rockpi-4b-rk3399.coffee
The rockpi-4b-rk3399 uses a different partitioning scheme
so let's set here the correct boot partition number.
Changelog-entry: Fix boot partition number in rockpi-4b-rk3399.coffee
> rockpi-4b-rk3399.coffee: Fix boot partition number

- layers/meta-balena-rockpi/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bbappend
We need this hook for u-boot based boards
Changelog-entry: Add missing u-boot hostapp update hook
> hostapp-update-hooks: Add missing u-boot hook

- layers/meta-balena-rockpi/recipes-core/images/balena-image.inc
Changelog-entry: balena-image: Install boot overlays in the root partition
> balena-image: Install boot overlays in the root partition

- layers/meta-balena-rockpi/recipes-kernel/linux/linux-rockpi-4b_%.bbappend
spidev kernel module is enabled by default in meta-balena, why not enable the spidev1 overlay by default on the rockpi-4b.
> linux-rockpi-4b: Load spidev1 overlay by default

- layers/meta-balena-rockpi/recipes-kernel/linux/linux-rockpi-4b_%.bbappend
Changelog-entry: Load spidev overlay by default
> linux-rockpi-4b: Load spidev overlay by default

- layers/meta-balena-rockpi/recipes-bsp/u-boot/files/0002-fs-fat-fix-wrong-casting-to-unsigned-value-of-sect_t.patch
- layers/meta-balena-rockpi/recipes-bsp/u-boot/u-boot-rockpi-4.bbappend
We backport an u-boot patch in order to fix the following:
writing bootcount.env
Error: Invalid FAT entry: 0x3ffffffa
Invalid FAT entry
Error: Invalid FAT entry: 0x3ffffffa
"Synchronous Abort" handler, esr 0x96000010
* Relocate offset = 00000000f5c07000
* ELR(PC)    =   0000000000262618
* LR         =   0000000000263b54
* SP         =   00000000f3df0a40
Changelog-entry: Backport u-boot fat fs related patch in order to fix write failure when saving bootcount
> u-boot-rockpi: Fix file write failure when saving bootcount

- layers/meta-balena-rockpi/recipes-core/images/balena-image.inc
The are currently incorectly installed
in the boot partition, instead of the overlays
directory. Let's fix that.
Changelog-entry: balena-image: Install overlays in correct directory
> [ESR BACKPORT] balena-image: Install overlays in correct directory

- layers/meta-balena-rockpi/recipes-core/images/balena-image.inc
The are currently incorectly installed
in the boot partition, instead of the overlays
directory. Let's fix that.
Changelog-entry: balena-image: Install overlays in correct directory
> balena-image: Install overlays in correct directory

- layers/meta-balena-rockpi/recipes-kernel/linux/linux-rockpi-4b_%.bbappend
load i2c7 bus by default as this is the main i2c bus on the 40 pin header, physical pins 3 and 5
Closes: #26 
Change-type: patch
Changelog-entry: Turn i2c7 bus on by default
Signed-off-by: Aaron Shaw <shawaj@gmail.com>
> linux-rockpi-4b: load i2c7 bus by default

- layers/meta-balena-rockpi/recipes-core/images/balena-image.inc
We spotted the following error in a meta-balena build PR, on the rockpi
extlinux.conf_flasher is an invalid path referenced in BALENA_BOOT_PARTITION_FILES
Changelog-entry: balena-image: ensure u-boot files are present when generating rootfs
Addresses error found in: https://github.com/balena-os/meta-balena/pull/2501 -> https://jenkins.product-os.io/job/yocto-rockpi-4b-rk3399/1472/console
> balena-image: ensure u-boot files are present when generating rootfs

- layers/meta-balena-rockpi/recipes-kernel/cypress-backports/brcmfmac.bb
We disable wireless powersave in order to fix latency issues:
https://github.com/balena-os/balena-rockpi/issues/49
Changelog-entry: Ensure wireless powersave if off by default
> brcmfmac.bb: Update brcmfmac to version that disables powersave

- layers/meta-balena-rockpi/recipes-bsp/u-boot/files/0003-Revert-cmd-nvedit-add-0x-prefix-for-hex-value.patch
- layers/meta-balena-rockpi/recipes-bsp/u-boot/u-boot-rockpi-4.bbappend
We revert the commit that converted the decimal number stored in the
bootcount environment variable to hex because when the environment
is updated then the bootcount comparison fails during the next boot
because it cannot compare numbers that use different bases.
Changelog-entry: Fix RockPi 4B hex bootcount issue for rollbacks
> u-boot-rockpi-4: Revert bootcount being saved in hex

- layers/meta-balena-rockpi/recipes-kernel/rkwifibt-firmware/rkwifibt-firmware.bbappend
This firmware will be used by boards having either the AP6212 or the
AzureWave AW-NB197SM wifi/bt chipsets.
Changelog-entry: Package newer bluetooth firmware for AP6212 based chips
> rkwifibt-firmware: Package newer bt firmware for AP6212 based chips

- layers/meta-balena-rockpi/recipes-bsp/u-boot/files/0001-Integrate-with-Balena-u-boot-environment_rockpi4b.patch
- layers/meta-balena-rockpi/recipes-bsp/u-boot/u-boot-rockpi-4.bbappend
The original intent needs additional work to make it function
as needed so let's revert the rework for now and we'll revisit
Changelog-entry: Revert the u-boot balena integration rework for RockPi 4B because it needed additional work
> u-boot-rockpi-4.bbappend: Revert the balena integration rework

- layers/meta-balena-rockpi/recipes-kernel/linux/files/0002-Revert-arm64-dts-rockchip-fix-ROCK-Pi-4-device-alias.patch
- layers/meta-balena-rockpi/recipes-kernel/linux/linux-rockpi-4_%.bbappend
The customer requested here https://jel.ly.fish/73928db3-83ea-4720-b754-3f9bb38bfcb4
to bring back the older spidev32766.0 node name:
https://github.com/radxa/kernel/blob/86a614bc15b3b1aeb3a9a9e395aedd088c70e35e/drivers/spi/spi.c#L1805-L1815
Changelog-entry: Revert device tree aliases for bringing back dynamic spi bus name numbering
> linux-rockpi-4_%.bbappend: Revert device tree aliases

- layers/meta-balena-rockpi/recipes-support/hostapp-update-hooks/files/1-bootfiles
We recently updated the BSP which in turn changed the dtb name.
We reflected the device tree name change in extlinux.conf but because
extlinux.conf is blacklisted then after a host OS update the new
extlinux.conf does not get copied over so the newer dtb does not
get loaded.
Changelog-entry: Remove extlinux.conf from blacklist
> hostapp-update-hooks: Remove extlinux.conf from blacklist

- layers/meta-balena-rockpi/conf/samples/bblayers.conf.sample
Yocto classes and conf files ignore layer priorities and are parsed
in order instead.
Changelog-entry: Modify layer ordering
Signed-off-by: Alex Gonzalez <alexg@balena.io>
> bblayers: Modify layer ordering

- layers/meta-balena-rockpi/conf/samples/bblayers.conf.sample
Perl is required for building efitools used for
EFI boot entry configuration and secure boot,
Changelog-entry: add meta-perl to bblayers.conf
Signed-off-by: Alex Gonzalez <alexg@balena.io>
> bblayers.conf.sample: add meta-perl

- layers/meta-balena-rockpi/recipes-kernel/linux/linux-rockpi-4_%.bbappend
Changelog-entry: linux-rockpi: Add scsi-generic driver
so the sd-mux can be used on this DT
Replaces https://github.com/balena-os/balena-radxa/pull/338
> linux-rockpi: Add scsi-generic driver

- .github/workflows/radxa-cm3-io-rk3566.yml
- .github/workflows/radxa-zero-s905y2.yml
- .github/workflows/rockpi-4b-rk3399.yml
Changelog-entry: Explicitly set GITHUB_TOKEN permissions for yocto workflow
> Explicitly set GITHUB_TOKEN permissions for yocto workflow

- layers/meta-balena-rockpi/recipes-bsp/rk-binary/radxa-binary-loader_%.bbappend
Changelog-entry: Update Radxa binary loader to new revision for supporting newer ROCK 4B SKUs
> radxa-binary-loader: Update to newer revision
